version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: anafob0330/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: anafob0330/kittygram_frontend
    env_file: .env
    depends_on:
      - backend  
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/static

  gateway:
    image: anafob0330/kittygram_gateway
    env_file: .env
    depends_on:
      - frontend  
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/app/media